web: java $JAVA_OPTS -jar target/dependency/webapp-runner.jar --port $PORT target/*.war
worker: java -war target/hotelmanagement-0.0.1-SNAPSHOT.war

web: java -jar target/hotelmanagement-0.0.1-SNAPSHOT.jar
worker: java -war target/hotelmanagement-0.0.1-SNAPSHOT.war